# Generated by Django 3.1.4 on 2020-12-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formu',
            old_name='amount',
            new_name='Sintoma_1',
        ),
        migrations.AddField(
            model_name='formu',
            name='Sintoma_2',
            field=models.IntegerField(default=666),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='Sintoma_3',
            field=models.IntegerField(default=666),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='Sintoma_4',
            field=models.IntegerField(default=666),
            preserve_default=False,
        ),
    ]
