# Generated by Django 3.1.4 on 2020-12-24 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201221_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='formu',
            name='Nombre_Paciente',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
