# Generated by Django 3.1.4 on 2020-12-24 01:50

from django.db import migrations, models

import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_formu_nombre_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='formu',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
