# Generated by Django 3.1.4 on 2020-12-24 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_formu_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formu',
            name='fecha',
        ),
        migrations.AddField(
            model_name='formu',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
