# Generated by Django 3.1.4 on 2020-12-24 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201223_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formu',
            name='date',
        ),
    ]
