# Generated by Django 3.1.4 on 2020-12-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_formu_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='formu',
            name='Nombre_Paciente2',
            field=models.CharField(default='sdasda', max_length=100),
            preserve_default=False,
        ),
    ]
