# Generated by Django 3.1.4 on 2020-12-24 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_formu_nombre_paciente2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formu',
            name='Nombre_Paciente2',
        ),
        migrations.AddField(
            model_name='formu',
            name='fecha_de_reporte',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
