# Generated by Django 3.1.4 on 2020-12-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201223_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='formu',
            name='Sintoma_10',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='Sintoma_5',
            field=models.IntegerField(default=123123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='Sintoma_6',
            field=models.IntegerField(default=1231231),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='Sintoma_7',
            field=models.IntegerField(default=1231),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='Sintoma_8',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='Sintoma_9',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
